Dummy Columns

In [3]:
import pandas as pd
df=pd.read_csv('car data.csv')
df.drop(columns=['Car_Name'],inplace=True)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [4]:
df = pd.get_dummies(df, columns=['Fuel_Type'], drop_first=True)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Seller_Type,Transmission,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol
0,2014,3.35,5.59,27000,Dealer,Manual,0,False,True
1,2013,4.75,9.54,43000,Dealer,Manual,0,True,False
2,2017,7.25,9.85,6900,Dealer,Manual,0,False,True
3,2011,2.85,4.15,5200,Dealer,Manual,0,False,True
4,2014,4.60,6.87,42450,Dealer,Manual,0,True,False
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Dealer,Manual,0,True,False
297,2015,4.00,5.90,60000,Dealer,Manual,0,False,True
298,2009,3.35,11.00,87934,Dealer,Manual,0,False,True
299,2017,11.50,12.50,9000,Dealer,Manual,0,True,False
300,2016,5.30,5.90,5464,Dealer,Manual,0,False,True

In [5]:
df = pd.get_dummies(df, columns=['Transmission'], drop_first=True)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Seller_Type,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Manual
0,2014,3.35,5.59,27000,Dealer,0,False,True,True
1,2013,4.75,9.54,43000,Dealer,0,True,False,True
2,2017,7.25,9.85,6900,Dealer,0,False,True,True
3,2011,2.85,4.15,5200,Dealer,0,False,True,True
4,2014,4.60,6.87,42450,Dealer,0,True,False,True
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Dealer,0,True,False,True
297,2015,4.00,5.90,60000,Dealer,0,False,True,True
298,2009,3.35,11.00,87934,Dealer,0,False,True,True
299,2017,11.50,12.50,9000,Dealer,0,True,False,True
300,2016,5.30,5.90,5464,Dealer,0,False,True,True

In [6]:
df = pd.get_dummies(df, columns=['Seller_Type'], drop_first=True)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Manual,Seller_Type_Individual
0,2014,3.35,5.59,27000,0,False,True,True,False
1,2013,4.75,9.54,43000,0,True,False,True,False
2,2017,7.25,9.85,6900,0,False,True,True,False
3,2011,2.85,4.15,5200,0,False,True,True,False
4,2014,4.60,6.87,42450,0,True,False,True,False
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,True,False,True,False
297,2015,4.00,5.90,60000,0,False,True,True,False
298,2009,3.35,11.00,87934,0,False,True,True,False
299,2017,11.50,12.50,9000,0,True,False,True,False
300,2016,5.30,5.90,5464,0,False,True,True,False

where Function

In [8]:
import numpy as np
df=pd.DataFrame({'Marks':[40,35,65,31,70,95,18]})
df['Result'] = np.where(df['Marks'] > 40, 'Pass', 'Fail')
df

   Marks Result
0     40   Fail
1     35   Fail
2     65   Pass
3     31   Fail
4     70   Pass
5     95   Pass
6     18   Fail

In [10]:
# Multiple conditions
df['Grade'] = np.where(df['Marks'] > 75, 'A',
np.where(df['Marks'] > 50, 'B', 'C'))
df

   Marks Result Grade
0     40   Fail     C
1     35   Fail     C
2     65   Pass     B
3     31   Fail     C
4     70   Pass     B
5     95   Pass     A
6     18   Fail     C

Mathematical Operation

In [11]:
df=pd.DataFrame({'Math':[45,60,75],'Science':[50,60,70]})
df['Total'] = df['Math'] + df['Science']
df['Average'] = df['Total'] / 2
df

   Math  Science  Total  Average
0    45       50     95     47.5
1    60       60    120     60.0
2    75       70    145     72.5

test_train_split

In [24]:
from sklearn.model_selection import train_test_split
df=pd.read_csv('car data.csv')
df.drop(columns=['Car_Name'],inplace=True)
df = pd.get_dummies(df,drop_first=True)
y=df['Selling_Price']
x=df.drop(columns=['Selling_Price'])

In [26]:
print("x=",x.shape)
print('y=',y.shape)

x= (301, 8)
y= (301,)

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [30]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(240, 8)
(61, 8)
(240,)
(61,)